#!/bin/bash

if [ $# -eq 0 ];then
	MESSAGE=auto
else
	MESSAGE=$1
fi

if [ $# -gt 1 ]; then 
	git config --global user.email "$2"
  git config --global user.name "$2"
fi

git add .
git commit -m "$MESSAGE"
git push